---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "springboot-demo"
  labels:
    project: "springboot-demo"
    version: "2.2.98-SNAPSHOT"
  annotations:
spec:
  template:
    spec:
      containers:
      - env:
        - name: "GOSUPERVISE_COMMAND"
          value: "/opt/springboot-camel-2.2.98-SNAPSHOT"
      serviceAccountName: "fabric8"
