---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "springboot-demo"
  labels:
    project: "springboot-demo"
    version: "{{ app_version }}"
  annotations:
spec:
  template:
    spec:
      containers:
      - env:
        - name: "GOSUPERVISE_COMMAND"
          value: "{{ app_home }}"
      serviceAccountName: "fabric8"
